version: "2"
linters:
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - misspell
    - unconvert
    - usestdlibvars
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - fizzbuzz
