{{- if gt (int .Values.autoscaling.minReplicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
